version: "3.8"

services:
  app:
    image: ${IMAGE_REPOSITORY}:${GIT_COMMIT_SHA}
    environment:
      - PATH=/home/node/.yarn/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - GANCIO_DATA=/home/node/data
      - NODE_ENV=production
      - GANCIO_HOST=0.0.0.0
      - GANCIO_PORT=13120
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - GANCIO_DB_DIALECT=postgres
      - GANCIO_DB_HOST=${DB_HOST}
      - GANCIO_DB_PORT=${DB_PORT}
      - GANCIO_DB_DATABASE=${DB_DATABASE}
      - GANCIO_DB_USERNAME=${DB_USERNAME}
      - GANCIO_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - gancio-data:/home/node/data
    networks:
      - infra_reverse-proxy
      - infra_postgres-net
    deploy:
      update_config:
        order: start-first
      restart_policy:
        condition: any

volumes:
  gancio-data:

networks:
  infra_reverse-proxy:
    external: true
  infra_postgres-net:
    external: true
